CREATE OR REPLACE TABLE USER_SCRATCH.X_JJAMES.HS_SST_SUB_DAILY_NEW AS(

WITH NEW_TABLE AS (

SELECT *,
CASE WHEN PREV_MONTH_LAST_DATE IS NULL THEN BILLING_UNIT_USD
ELSE 0
END AS NEW_MRR ,

// Planned Churn
CASE WHEN (CALCULATED_STATUS = 'CANCELED') 
AND DS=TERM_END_DATE THEN BILLING_UNIT_USD 
ELSE 0
END AS PLANNED_CHURN,

// Unplanned Churn
CASE WHEN DS=CANCELLATION_DS AND DS < TERM_END_DATE THEN BILLING_UNIT_USD 
ELSE 0
END AS UNPLANNED_CHURN,
0 AS UPLIFT,
0 AS DOWNGRADE,

CASE WHEN CONTRACT_START_DATE BETWEEN FIRST_DAY_OF_MONTH AND LAST_DAY_OF_MONTH THEN NEW_MRR-PLANNED_CHURN-UNPLANNED_CHURN
ELSE 0
END AS ENDING_MRR,

CASE WHEN (TERM_END_DATE > PRIOR_TERM_END_DATE)OR(BILLING_UNIT_USD != PRIOR_BILLING_AMT) THEN BILLING_UNIT_USD
ELSE 0
END AS RENEWED_MRR

-- CASE WHEN (NEW_MRR+BEGINNING_MRR-RENEWED_MRR) AS ENDING_MRR

FROM(
SELECT 
A.DS::DATE AS DS,
CONTRACT_NUMBER,
A.LOCATION_ID,
A.PRODUCT,
BILLING_ACCOUNT_ID,
'NO_AID' AS ADVERTISER_ID,
'NO_CID' AS CAMPAIGN_ID,
CONTRACT_START_DATE,
-- DAY(A.DS::DATE) AS DAYS,
-- MONTH (A.DS::DATE) AS MONTH,
-- YEAR(A.DS::DATE) AS YEAR,
TERM_START,
TERM_END,
TERM_START_DATE,
TERM_END_DATE, 
MIN(TERM_START_DATE) OVER(PARTITION BY A.LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT, MONTH, YEAR ORDER BY A.DS ASC ) AS MIN_START_DATE,
MIN(TERM_END_DATE) OVER(PARTITION BY A.LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT, MONTH, YEAR ORDER BY A.DS ASC ) AS MIN_END_DATE,
CASE WHEN MIN_START_DATE BETWEEN FIRST_DAY_OF_MONTH AND LAST_DAY_OF_MONTH THEN NULL
ELSE TO_DATE(DATEADD(DAY,-1,FIRST_DAY_OF_MONTH))
END AS PREV_MONTH_LAST_DATE,
CANCELLATION_DS,
CONTRACT_FREE_TRIAL,
CALCULATED_STATUS,
FIRST_DAY_OF_MONTH,
LAST_DAY_OF_MONTH,
PRODUCT_DESCRIPTION,
C.COUNTRY,
C.GEO_ID,
C.GEO_NAME,
C.PLACE_TYPE,
C.PROPERTY_NAME,
DAY_START_CONTRACT_STATUS,
DAY_END_CONTRACT_STATUS,
CONTRACT_BILLING_UNIT_AMT_PER_LOCATION_USD AS BILLING_UNIT_USD,
CONTRACT_BILLING_UNIT_DISCOUNT_FIXED_AMT AS DISCOUNT_AMT,
CONTRACT_BILLING_PERIOD_DISCOUNT_PERCENTAGE AS DISCOUNT_PCT,
CONTRACT_BILLING_UNIT_NET_AMT_PER_LOCATION_USD AS NET_BILLING_UNIT_USD,
CASE WHEN 
A.CANCELLATION_DS = A.DS THEN 1 ELSE 0 END AS CANCELED_FLAG,
CASE 
    WHEN CALCULATED_STATUS != 'CANCELED' 
    THEN LAG (CONTRACT_BILLING_UNIT_AMT_PER_LOCATION_USD) OVER (PARTITION BY A.LOCATION_ID, BILLING_ACCOUNT_ID, CONTRACT_NUMBER, PRODUCT ORDER BY A.DS ASC) 
    ELSE 0 END PRIOR_BILLING_AMT,
CASE WHEN 
    LAG (A.DS) OVER (PARTITION BY A.LOCATION_ID, BILLING_ACCOUNT_ID, CONTRACT_NUMBER, PRODUCT ORDER BY A.DS ASC) IS NOT NULL THEN 1 ELSE 0 
    END AS PRIOR_DATE_ACTIVE,
CASE WHEN 
    CALCULATED_STATUS = 'CANCELED' THEN MIN(A.DS) OVER (PARTITION BY A.LOCATION_ID, BILLING_ACCOUNT_ID, CONTRACT_NUMBER, PRODUCT ORDER BY A.DS ASC) 
    END AS MIN_CANCEL_DATE,
LAG (TERM_END_DATE) OVER (PARTITION BY A.LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT ORDER BY A.DS ASC) AS PRIOR_TERM_END_DATE

from rio_sf.b2b_core.vw_contract_location_daily a
join rio_sf.b2b_core.t_calendar b on a.ds = b.ds
join RIO_SF.HOTELS_SST.A_LOCATION_DETAILS_DAILY c on a.location_id = c.location_id and a.ds = c.ds
WHERE A.LOCATION_ID = 10006128
AND CONTRACT_NUMBER = 'CS-000000182760' 
ORDER BY a.DS::DATE))

SELECT *,

CASE WHEN NEW_MRR>0 THEN 0
     WHEN NEW_MRR = 0 AND DS= FIRST_DAY_OF_MONTH THEN (LAG(ENDING_MRR) OVER(PARTITION BY LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT ORDER BY DS ASC))
     -- WHEN NEW_MRR=0 AND DS!= FIRST_DAY_OF_MONTH THEN LAG(ENDING_MRR,DAYS,0) OVER(PARTITION BY LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT ORDER BY DS ASC)
END AS BEGINNING_MRR

-- CASE WHEN RENEWED_MRR = 0 
--      AND (LAG(RENEWED_MRR) OVER (PARTITION BY  LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT ORDER BY DS ASC))!=0
--      AND DS <= LAST_DAY_OF_MONTH 
--      THEN (LAG(RENEWED_MRR) OVER (PARTITION BY  LOCATION_ID,BILLING_ACCOUNT_ID,CONTRACT_NUMBER, PRODUCT ORDER BY DS ASC))
--      ELSE RENEWED_MRR
-- END AS RENEWED_MRR_2

FROM NEW_TABLE);

-- SELECT * FROM USER_SCRATCH.X_JJAMES.HS_SST_SUB_DAILY_NEW;


